spring:
  kafka:
    bootstrap-servers: kafka:9094
    ssl:
      protocol: PLAINTEXT #SSL
      trust-store-location: file:/app/store/truststore.jks
      trust-store-password: <TRUST_STORE_PASSWORD>
      key-store-location: file:/app/store/keystore.jks
      key-store-password: <KEY_STORE_PASSWORD>
      key-password: <KEY_PASSWORD>
# https://codingnconcepts.com/spring-boot/configure-kafka-producer-and-consumer/
# It is recommended to always give absolute path in production environment to avoid any error.

# Absolute Path
# file:/app/store/truststore.jks

# Relative Path
# file:app/store/truststore.jks
  cloud:
    openfeign:
      client:
        config:
          books:
            url: http://server:8189/book-find/api/v1/books