server:
  port: 8189
  servlet:
    context-path: /book-find
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookfind?currentSchema=public
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:/db/postgresql/common,/db/postgresql/prod