server:
  port: 8189
  servlet:
    context-path: /book-find
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:/db/postgresql/common,/db/postgresql/test
  jackson:
    serialization:
      indent_output: true
  mail:
    host: 192.168.1.6 #smtp.gmail.com book-find.ru #
    port: 25
    protocol: smtp
    username:
    password:
    templates:
      path: /templates
    properties:
      mail:
        smtp:
          auth: false #true
          starttls:
            enable: false #true # Enable a TLS-protected connection.
  web:
    resources:
      static-locations: file:src/main/resources/static/
jwt:
  secret:
support:
  email: "info@book-find.ru"
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
#      path: /h2
#
#logging:
#  level.ru.dsci.stockdock.* : debug
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread]: %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.sss} [%thread] %-5level %logger{36}: %msg%n"
#  file:
#    name: logs/dev/stockdock.log
#    path: logs/dev