server:
  port: 8189
  servlet:
    context-path: /book-find
spring:
  #  https://stackoverflow.com/questions/40241843/failed-to-start-bean-documentationpluginsbootstrapper-in-spring-data-rest
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookfind_test?currentSchema=main
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:/db/postgresql/common,/db/postgresql/dev
  jackson:
    serialization:
      indent_output: true
  mail:
    host: 192.168.1.6 #smtp.gmail.com book-find.ru #
    port: 25
    protocol: smtp
    username:
    password:
    templates:
      path: /templates
    properties:
      mail:
        smtp:
          auth: false #true
          starttls:
            enable: false #true # Enable a TLS-protected connection.
  web:
    resources:
      static-locations: file:src/main/resources/static/
jwt:
  secret:
support:
  email: "info@book-find.ru"

#  logging.level.root=INFO
#  logging.level.org.springframework.security=DEBUG
#  spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true