server:
  ssl:
    enabled: false
#  error:
#    include-stacktrace: never
spring:
  #  main:
  #    lazy-initialization: true see BooksIntegration Test: @ComponentScan(lazyInit = true)

  #  https://stackoverflow.com/questions/40241843/failed-to-start-bean-documentationpluginsbootstrapper-in-spring-data-rest
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  datasource:
    #url: jdbc:postgresql://localhost:5432/bookfind_test?currentSchema=main #public
    ##url: jdbc:postgresql://localhost:5433/ #new version
    #username:
    #password:
    url: jdbc:mariadb://192.168.1.6:3307/bookfind_test
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        #dialect: org.hibernate.dialect.PostgreSQL95Dialect
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    open-in-view: true
  flyway:
    #locations: classpath:/db/postgresql/common,/db/postgresql/dev
    locations: classpath:/db/mariadb/common,/db/mariadb/dev
  jackson:
    serialization:
      indent_output: true
  kafka:
    ssl:
      protocol: PLAINTEXT
  mail:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  web:
    resources:
      static-locations: file:src/main/resources/static/
jwt:
  secret:
support:
  email: "info@book-find.ru"

#  logging.level.root=INFO
#  logging.level.org.springframework.security=DEBUG
#  spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true
