server:
  port: 8189
  servlet:
    context-path: /book-find
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
          use_jdbc_metadata_defaults: false
  flyway:
    locations: classpath:/db/postgresql/common,/db/postgresql/test
  jackson:
    serialization:
      indent_output: true
  web:
    resources:
      static-locations: file:src/main/resources/static/