server:
  ssl:
    enabled: false #true
    key-store: classpath:www.book-find.ru.jks
    key-store-type: pkcs12
    key-store-password:
    #key-password:
    key-alias:
    #certificate-private-key:
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/bookfind?currentSchema=main #public
    ##url: jdbc:postgresql://localhost:5433/ #new version
    #username:
    #password:
    url: jdbc:mariadb://192.168.1.6:3307/bookfind
    username:
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        #dialect: org.hibernate.dialect.PostgreSQL95Dialect
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true #false
  flyway:
    #locations: classpath:/db/postgresql/common,/db/postgresql/prod
    locations: classpath:/db/mariadb/common,/db/mariadb/prod
  kafka:
    ssl:
      protocol: PLAINTEXT #SSL
      trust-store-location: file:/app/store/truststore.jks
      trust-store-password: <TRUST_STORE_PASSWORD>
      key-store-location: file:/app/store/keystore.jks
      key-store-password: <KEY_STORE_PASSWORD>
      key-password: <KEY_PASSWORD>
  # https://codingnconcepts.com/spring-boot/configure-kafka-producer-and-consumer/
  # It is recommended to always give absolute path in production environment to avoid any error.

  # Absolute Path
  # file:/app/store/truststore.jks

  # Relative Path
  # file:app/store/truststore.jks
  mail:
    properties:
      mail:
        smtp:
          auth: false #true
          starttls:
            enable: false #true # Enable a TLS-protected connection.
jwt:
  secret:
